modLoader="kotlinfml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/shadowfacts/Forgelin/issues"
displayURL="https://github.com/shadowfacts/Forgelin"
logoFile="examplemod.png"
credits="Emberwalker, for the original Forgelin"
authors="shadowfacts" #optional

[[mods]]
    modId="forgelin"
    version="2.0.0"
    displayName="Shadowfacts' Forgelin"
    #updateJSONURL="" #optional
    description="Kotlin provider for Forge."

[[dependencies.forgelin]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.forgelin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,)"
    ordering="NONE"
    side="BOTH"